# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-25 21:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseballproject', '0002_auto_20170620_0318'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='contest',
            field=models.CharField(choices=[(b'fanduel', b'FANDUEL'), (b'draftkings', b'DRAFTKINGS'), (b'yahoo', b'YAHOO')], default=b'fanduel', max_length=10),
        ),
    ]
