# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-26 02:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseballproject', '0003_document_contest'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='document',
            table='profile',
        ),
    ]
