# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-26 02:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseballproject', '0005_auto_20170625_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='contest',
            field=models.CharField(choices=[(b'fanduel', b'FANDUEL'), (b'draftkings', b'DRAFTKINGS'), (b'yahoo', b'YAHOO')], default=b'FANDUEL', max_length=10),
        ),
        migrations.AlterModelTable(
            name='document',
            table='profile',
        ),
    ]
