# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 05:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseballproject', '0006_auto_20170625_2246'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='document',
            table='contestInfo',
        ),
    ]
